### ISSUE TITLE
Incorrectly listed as "known not Turing-complete"

### ISSUE THREAD

**Issue by HactarCE** [catseye/Circute#1]
On the Catseye website, Circute is listed as "known not Turing-complete," but it clearly is. I have recreated Circute in [Golly](http://golly.sourceforge.net/), and created several constructions which should prove that Circute is theoretically able to emulate any computer (thus making it Turing-complete). (The NAND gate is cyan instead of blue and the background is dark grey instead of white.)

Any traditional logic gate can be constructed as per [this Wikipedia page](https://en.wikipedia.org/wiki/NAND_logic), including...

An XOR gate, which can be used to construct a wire crossing
![image](https://user-images.githubusercontent.com/6060305/28674646-fda9d7a8-72b3-11e7-82e6-ae3a00591748.png)

An SR flip-flop made of two NOR gates
![image](https://user-images.githubusercontent.com/6060305/28675445-e7c7ba0c-72b5-11e7-924b-10bd238c0681.png)
(inputs on the left, outputs on the right)

These two, combined with any logic gate listed on the Wikipedia page, should be much more than sufficient to deem this automaton Turing-complete. It has signal transmission, memory storage, and every digital logic gate.

([Here's the rule file if you want to try it out.](https://pastebin.com/kXXVeFqK))

**Comment by cpressey** [comment]
Thanks, but how do you figure that "signal transmission, memory storage, and every digital logic gate" is sufficient for Turing-completeness?  Turing machines have unlimited memory, and can halt.  Circute configurations are finite and, being cellular automata, never halt.  So if you wanted to simulate an arbitrary Turing machine in Circute, you'd need an infinitely large Circute configuration, and a definition of what it means for it to have halted.  And those things are beyond the definition of Circute per se.

**Comment by HactarCE** [comment]
A Turing machine's memory does not need to be infinite, just as large as the problem demands. A cell could be defined as the "halting cell", such that the machine halts when that cell becomes a certain state (or when a group of cells matches a particular pattern). At the very least, a system could be constructed in Circute which simulates Wireworld or Conway's Life, which have both been proven to be Turing-complete. Is my computer not Turing-complete because it has finite RAM and disk space?

**Comment by cpressey** [comment]
> A Turing machine's memory does not need to be infinite, just as large as the problem demands.

There is a Turing machine that writes a 1 symbol to its tape, moves its tape head one cell to the right, and repeats.  This machine never halts, and its tape always keeps growing.  Do you propose that this can be accurately simulated on a machine with a finite memory?

> A cell could be defined as the "halting cell"

*Could* be, sure, but isn't.  Are we allowed to extend definitions of things arbitrarily so that we can simulate Turing machines with them?  If we are, then where do we stop?  I prefer not to start.

> At the very least, a system could be constructed in Circute which simulates Wireworld or Conway's Life, which have both been proven to be Turing-complete.

If you're referring to the proofs that I think you are, they are of the form "These CAs are Turing-complete, if we are allowed to fill the cellular automaton's playfield with an infinite pattern intially, and if we consider them to have halted if such-and-such condition pertains."  Which is what I was talking about in the previous comment.

In the past I've used the term "CA-complete" to mean "Can simulate any cellular automaton", and maybe it applies here, I don't know.  There is very likely a way to map Circute configurations onto Wireworld configurations and vice versa.  But to simulate Life, you'd need to fill the Circute playfield with an infinite repeating pattern at the start, so I'm not sure.  (Gliders can spin off forever into space, but sparks can't.)

> Is my computer not Turing-complete because it has finite RAM and disk space? What about BF, simulated with a finite array of cells which only encode 0-255?

Well, your computer is a physical machine, not a language.  But if you mean, the language of your physical machine -- no, it's not.  There are Turing machines that your machine cannot simulate.  There are Turing machines that cannot be simulated by a version of brainfuck which has a finite number of finitely-sized cells.

There are, on the other hand, finite automata (very large ones) that can simulate those things, yes?

And the fact that Turing machines can recognize a strictly larger class of languages than finite automata is very well established in computability theory.

Yes, with some "fudging", Circute (or your physical computer's machine language) would be Turing-complete, I don't disagree with you on that.  But I don't see the motivation for such fudging.  And, as I said, once you've started, where do you stop?  Why not say that finite automata are Turing-complete *if* you simply make them infinitely large?

**Comment by rodrigosetti** [comment]
It's impossible to implement a mathematical Turing machine in the physical universe due to limitations of memory, but Circuite is as powerful as any programming language (or digital circuit for that matter) - they also don't have an "external" mechanism for halting, as it's just our interpretation of what halting means (i.e. a programming language never halts, it just sends a message to the operating system, which is interpreted as "exit" and the OS terminates the process for them).

**Comment by cpressey** [comment]
@rodrigosetti I find it very difficult to understand what you mean by "A programming language never halts".  Literally _every_ programming language defines the conditions under which a program written in that language terminates.  If it didn't, programmers probably wouldn't use it!

Note that "As powerful as any programming language" is an informal statement.  "Turing-complete" is a formal statement.

Circute and Turing machines are both formal automata; they can both be viewed as a sequence of configurations equipped with a relation between configurations.  For Circute, that relation is always defined; for every configuration there is a configuration that comes next.  For a Turing machine, that relation is only partial; when the Turing machine is in a halting state, no next configuration exists.

You can of course define some minor variation on Circute, call it (say) Circute++, where the sequence of configurations is defined to terminate when such-and-such predicate is true.  You can then go on to prove something about Circute++.  But does that proof automatically apply to Circute as well?  No, because in order to claim it applies to Circute, you would need to actually show that, because of the fact that it applies to Circute++, it must apply to Circute too.  But if that proof hinges on a property that Circute++ has but Circute lacks, then it's just not possible to do that.

**Comment by rodrigosetti** [comment]
Apologies for the loose statements, let me clarify:

One interpretation of general-purpose programming languages is that they describe pure algorithms but need to communicate with the real world to do useful things (such as reading user input, printing, etc.). In operating systems, this communication (mostly) happens with syscalls. One of these is the ["exit" call](https://en.wikipedia.org/wiki/Exit_(system_call)), which effectively terminates the program. Therefore, technically, what terminates the program is the OS, not really the program. So there is a semantic "outside" the programming language that defines what halting means.

Therefore, all programming languages are like Circuite++ in the sense that they have a contract with the OS such that when a particular instruction is executed, the OS terminates it.

Another way to put it: NAND gates and wires are Turing complete because one can implement a Turing machine using these. NAND and wires technically never "halt" (unless you unplug the power), therefore the semantic of what halting means has to be defined. Computers are transistors and wires, and the only way to "halt" a computer is to unplug the cord - a behavior external to the transistors+wires system, although modern computers

Physics is turning complete too (in fact, more powerful than turning machines thanks to quantum mechanics), because computers can be constructed in the real world. But Physics can't be halted. The computers implemented using electronics defines the semantics of what halting means.

A similar cellular automaton to Circuite is [Wireworld](https://en.wikipedia.org/wiki/Wireworld), and it is Turing-Complete. Wireworld is almost identical to Circuite, except that it lacks NAND gates (also, it uses [Moore neighborhood](https://en.wikipedia.org/wiki/Moore_neighborhood), and the WIRE->SPARK rules is a little different). People have [implemented a programmable computer](https://en.wikipedia.org/wiki/Moore_neighborhood) on it.

A Turing-complete system is one where one can use the primitives to implement a Turing Machine and define the semantics of what halting means. Circuite is one of those systems.

**Comment by andycmo** [comment]
I came across this thread while working on WireWorld unit cells and I was able to port a Rule 110 unit cell to Circuite. Because Rule 110 is proven Turing-complete this means that Circute is also Turing-complete.

Processing element
![rule-110-processing-element](https://user-images.githubusercontent.com/82992985/115656901-96641600-a368-11eb-9136-66cfa162c2af.png)

Unit cell and test cases
![rule-110](https://user-images.githubusercontent.com/82992985/115656331-a8918480-a367-11eb-8a7a-551bc85e0bd5.png)

Unit cell grid
![rule-110-grid](https://user-images.githubusercontent.com/82992985/115656345-ab8c7500-a367-11eb-826a-6b850b283ef2.png)

Golly copy/paste 
[rule-110-unit-cell.txt](https://github.com/catseye/Circute/files/6355588/rule-110-unit-cell.txt)

**Comment by andycmo** [comment]
Here's a more compact version with corrected signal timings

![rule-110-compact](https://user-images.githubusercontent.com/82992985/115662787-1478ea80-a372-11eb-8e23-48e40e87a904.png)

[rule-110-unit-cell-compact.txt](https://github.com/catseye/Circute/files/6355844/rule-110-unit-cell-compact.txt)

**Comment by cpressey** [comment]
The claim that the Rule 110 cellular automaton is Turing-complete also rests on the idea that reductions between constructions that never halt (i.e. cellular automata) and conjstructions that may or may not halt (i.e. Turing machines) are valid reductions to use in proofs of Turing-completeness.  I reject that idea, and I've already stated the reasons why I reject that idea.  Closing this issue as non-productive.
